import { GetAllUserPages } from "@/actions/page/GetAllUserPages";
import { Metadata } from "next"
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { GetUser } from "@/actions/user/GetUser";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { CreateNewPage } from "@/components/shared/CreateNewPage";
import { SquareArrowOutUpRight } from "lucide-react";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
    title: "Astralics | Choose Page",
    description: "Generated by create next app",
};
  
export default async function Page() {
    const session = await auth();
    if(!session) redirect('/login');
    const user = await GetUser();
    const pages = await GetAllUserPages();
    return (
        <>
        <div className="flex items-center justify-center py-24">
        <div className="mx-auto grid w-[350px] gap-6">
          <div className="grid gap-2 text-center">
            <h1 className="text-3xl font-bold">Choose Page</h1>
          </div>
          <div className="grid gap-4">
            <div className="-mt-1">
              <Separator />
            </div>
            {pages.pages?.pages?.map((page:Page) => {
                return (
                    <>
                    <Button variant="outline" asChild className="w-full">
                        <Link href={`/app/${page.slug}/overview`}>
                            {page.name}
                        </Link>
                    </Button>
                    </>
                )
            })}
          </div>
        </div>
        </div>
        </>
    )
}